"""add operation log table

Revision ID: 1a2c7a929805
Revises: 8a37465e4528
Create Date: 2026-08-22 17:08:06.872904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2c7a929805'
down_revision: Union[str, Sequence[str], None] = '8a37465e4528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('server_seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_op_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('op_type', sa.Enum('create', 'update', 'delete', name='op_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
    sa.Enum(name='op_type').drop(op.get_bind(), checkfirst=True)
