"""add user profiles table

Revision ID: 22421a5702d3
Revises: 5fcbce5d92ac
Create Date: 2026-08-21 18:41:58.185455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22421a5702d3'
down_revision: Union[str, Sequence[str], None] = '5fcbce5d92ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex_at_birth', sa.Enum('female', 'male', 'intersex', 'prefer_not_to_say', name='sex_at_birth'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('timezone', sa.String(), server_default='UTC', nullable=False),
    sa.Column('locale', sa.String(), server_default='en', nullable=False),
    sa.Column('unit_system', sa.Enum('metric', 'imperial', name='unit_system'), server_default='metric', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
    sa.Enum(name='sex_at_birth').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='unit_system').drop(op.get_bind(), checkfirst=True)
