"""add entity field versions table

Revision ID: 22cafa0c8dce
Revises: 93b404b1d4a9
Create Date: 2026-08-22 17:26:43.413574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cafa0c8dce'
down_revision: Union[str, Sequence[str], None] = '93b404b1d4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_field_versions',
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'field_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_field_versions')
    # ### end Alembic commands ###
