"""add totp mfa columns

Revision ID: 72086a643a96
Revises: 55f6ea54e25b
Create Date: 2026-08-22 10:21:34.172548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72086a643a96'
down_revision: Union[str, Sequence[str], None] = '55f6ea54e25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_totp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_totp_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_totp_enabled')
    op.drop_column('users', 'mfa_totp_secret')
    # ### end Alembic commands ###
