"""index operation log

Revision ID: 93b404b1d4a9
Revises: 1a2c7a929805
Create Date: 2026-08-22 17:12:59.192022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b404b1d4a9'
down_revision: Union[str, Sequence[str], None] = '1a2c7a929805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_operations_user_id_server_seq', 'operations', ['user_id', 'server_seq'], unique=False)
    op.create_unique_constraint('uq_operations_user_id_client_op_id', 'operations', ['user_id', 'client_op_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_operations_user_id_client_op_id', 'operations', type_='unique')
    op.drop_index('ix_operations_user_id_server_seq', table_name='operations')
    # ### end Alembic commands ###
