"""add totp replay protection column

Revision ID: febf0859fa1c
Revises: 72086a643a96
Create Date: 2026-08-22 10:27:52.246318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febf0859fa1c'
down_revision: Union[str, Sequence[str], None] = '72086a643a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_totp_last_used_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_totp_last_used_step')
    # ### end Alembic commands ###
